version: '3.8'

services:
  odoo:
    image: odoo:18
    container_name: odoo
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    volumes:
      - odoo_data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
    ports:
      - "8069:8069"
    depends_on:
      - db
    networks:
      - odoo-network

  db:
    image: postgres:13
    container_name: odoo-db
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_DB=odoo
    volumes:
      - odoo_db_data:/var/lib/postgresql/data
    networks:
      - odoo-network

volumes:
  odoo_data:
  odoo_db_data:

networks:
  odoo-network:
    driver: bridge
